import test from 'node:test';
import assert from 'node:assert/strict';
import {createSteps,verifyStep,closureState,makeLedgerEntry} from '../src/engine.js';
const one=()=>createSteps()[0];
test('all five normal steps can pass; human approval remains separate',()=>{const steps=createSteps(),results=Object.fromEntries(steps.map(s=>[s.id,verifyStep(s)]));assert.ok(closureState(steps,results).allowed)});
test('confirmed absence of call record is mismatch',()=>assert.equal(verifyStep(createSteps('mismatch')[0]).status,'MISMATCH'));
test('no response is insufficient, not a confirmed absence',()=>{const s=one();s.proof.kind='no_response';assert.equal(verifyStep(s).status,'INSUFFICIENT')});
test('wrong target blocks verification',()=>{const s=one();s.claim.target='P-9999';assert.equal(verifyStep(s).status,'IDENTITY_MISMATCH')});
test('time tolerance includes 15 minutes but excludes 16',()=>{const s=one();s.claim.time='18:47';assert.equal(verifyStep(s).status,'VERIFIED');s.claim.time='18:48';assert.equal(verifyStep(s).status,'MISMATCH')});
test('invalid time cannot pass',()=>{const s=one();s.claim.time='25:00';assert.equal(verifyStep(s).status,'INVALID')});
test('wrong action and issuer cannot pass',()=>{const s=one();s.claim.action='CCTV_CHECK';assert.equal(verifyStep(s).status,'MISMATCH');const p=one();p.proof.issuer='OTHER';assert.equal(verifyStep(p).status,'MISMATCH')});
test('both records reporting failure do not satisfy completion',()=>{const s=one();s.claim.success=false;s.proof.success=false;assert.equal(verifyStep(s).status,'INCOMPLETE')});
test('false success claim is mismatch',()=>{const s=one();s.proof.success=false;assert.equal(verifyStep(s).status,'MISMATCH')});
test('CCTV missing within 12 hours warns even without a claim',()=>assert.equal(verifyStep(createSteps('deadline')[3]).status,'EXPIRING_SOON'));
test('already expired evidence is not merely expiring soon',()=>{const s=createSteps('deadline')[3];s.deadline='2026-09-13T18:59:00+09:00';assert.equal(verifyStep(s).status,'EXPIRED')});
test('deadline threshold covers exactly 24 hours',()=>{const s=createSteps('deadline')[3];s.deadline='2026-09-14T19:00:00+09:00';assert.equal(verifyStep(s).status,'EXPIRING_SOON')});
test('empty and partially verified cases cannot close',()=>{assert.equal(closureState([],{}).allowed,false);assert.equal(closureState(createSteps(),{1:verifyStep(one())}).allowed,false)});
test('scenario data has independent mutable records',()=>{const a=createSteps(),b=createSteps();a[0].claim.target='X';assert.equal(b[0].claim.target,'P-1872')});
test('hash describes content, links to prior record, and never claims a chain transaction',async()=>{const a=await makeLedgerEntry({type:'test',claim:'A'}),b=await makeLedgerEntry({type:'test',claim:'B'},a.hash);assert.match(a.hash,/^[a-f0-9]{64}$/);assert.notEqual(a.hash,b.hash);assert.equal(b.previous_hash,a.hash);assert.equal(b.on_chain,false)});
