import React,{useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {ACTIONS,STATUS,SCENARIOS,DEMO_TIME,createSteps,verifyStep,closureState,makeLedgerEntry} from './engine.js';

function Badge({status='PENDING'}){const s=STATUS[status]??STATUS.PENDING;return <span className={'status '+s.tone}>{s.label}</span>}
const prettyTime=t=>new Date(t).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});

export default function DemoApp(){
 const [scenario,setScenario]=useState('normal'),[steps,setSteps]=useState(()=>createSteps()),[selected,setSelected]=useState(1),[results,setResults]=useState({}),[view,setView]=useState('case'),[ledger,setLedger]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[reason,setReason]=useState(''),[closed,setClosed]=useState(false),[confirm,setConfirm]=useState(false),[reviewed,setReviewed]=useState(false);
 const lock=useRef(false), generation=useRef(0);
 useEffect(()=>{if(!confirm)return;const previous=document.activeElement;const dialog=document.querySelector('[role="dialog"]');const focusable=()=>Array.from(dialog?.querySelectorAll('button:not([disabled])')??[]);const key=e=>{if(e.key!=='Tab')return;const items=focusable(),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};dialog?.addEventListener('keydown',key);return()=>{dialog?.removeEventListener('keydown',key);previous?.focus()};},[confirm]);
 const step=steps.find(s=>s.id===selected),result=results[selected],closure=closureState(steps,results),count=Object.values(results).filter(r=>r.completed).length;
 function reset(id=scenario){generation.current++;setScenario(id);setSteps(createSteps(id));setSelected(id==='deadline'?4:1);setResults({});setView('case');setLedger([]);setNotice('새 시연을 시작했습니다.');setReason('');setClosed(false);setConfirm(false);setReviewed(false)}
 function edit(field,value){setSteps(a=>a.map(s=>s.id===selected?{...s,claim:{...s.claim,[field]:value}}:s));setResults(r=>{const n={...r};delete n[selected];return n});setReviewed(false);setNotice('입력이 변경되어 다시 검증해야 합니다.');}
 async function run(all=false){
  if(lock.current||closed)return;lock.current=true;setBusy(true);setNotice('');const current=generation.current;
  try{
   const target=all?steps:[step],next={...results},entries=[];let previous=ledger.at(-1)?.hash??null;
   for(const s of target){
    let answer;
    if(import.meta.env.VITE_VERIFICATION_API){
     const response=await fetch(import.meta.env.VITE_VERIFICATION_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({step:s,now:DEMO_TIME}),signal:AbortSignal.timeout(10000)});
     if(!response.ok)throw new Error('검증 서버에 연결하지 못했습니다. 잠시 후 다시 시도하세요.');
     answer=await response.json();if(!STATUS[answer.status]||!Array.isArray(answer.checks))throw new Error('검증 응답 형식을 확인할 수 없습니다.');
    }else answer=verifyStep(s);
    next[s.id]=answer;
    const entry=await makeLedgerEntry({type:'verification',scenario,step_id:s.id,step_name:s.name,claim:s.claim,proof:s.proof,result:answer},previous);previous=entry.hash;entries.push(entry);
   }
   if(current!==generation.current)return;
   setResults(next);setLedger(a=>[...a,...entries]);setReviewed(false);setNotice(all?'5개 수사 단계 검증을 완료했습니다.':'검증 결과와 대조 근거를 확인하세요.');
  }catch(e){setNotice(e.message||'검증 중 오류가 발생했습니다.');}finally{lock.current=false;setBusy(false)}
 }
 async function saveReview(close=false){
  if(lock.current||closed||!reason.trim()||(close&&!closure.allowed))return;
  lock.current=true;setBusy(true);try{
   const entry=await makeLedgerEntry({type:close?'closure':'review',scenario,reviewer:'시연 관리자',reason:reason.trim(),decision:close?'CLOSED':'FOLLOW_UP_REQUIRED',blockers:closure.blockers.map(s=>s.id)},ledger.at(-1)?.hash??null);
   setLedger(a=>[...a,entry]);setReviewed(true);setConfirm(false);setNotice(close?'관리자가 최종 확인하여 시연 사건을 종결했습니다.':'확인 사유와 보완 요청을 세션 기록에 저장했습니다.');if(close)setClosed(true);
  }catch{setNotice('확인 기록을 저장하지 못했습니다. 다시 시도하세요.')}finally{lock.current=false;setBusy(false)}
 }
 function download(){const blob=new Blob([JSON.stringify({project:'FullProof',demo:true,scenario,reference_time:DEMO_TIME,closed,ledger},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='fullproof-demo-records.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 const currentState=useRef();currentState.current={scenario,view,selected,results,closed};
 useEffect(()=>{const ctx=document.modelContext;if(!ctx?.registerTool)return;const life=new AbortController();
  const tools=[{name:'fullproof_read_demo',description:'Read the active simulated case and verification results. No real investigation data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>currentState.current},
   {name:'fullproof_start_scenario',description:'Start a demo scenario and clear current temporary demo results and review notes.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:['normal','mismatch','deadline']}},required:['scenario'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||Object.keys(input).length!==1||!SCENARIOS.some(s=>s.id===input.scenario))throw new Error('Invalid scenario');if(lock.current)throw new Error('Verification in progress');flushSync(()=>reset(input.scenario));return currentState.current}}];
  for(const t of tools)try{Promise.resolve(ctx.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}
  return()=>life.abort();
 },[]);
 return <div className="shell"><a className="skip-link" href="#main-content">본문으로 이동</a><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView('case')}}><em>F·</em><span>FULLPROOF<small>INVESTIGATION WORKSPACE</small></span></a><div className="workspace-label">WORKSPACE / AIF4</div><nav aria-label="워크스페이스 메뉴">{[['case','사건 검증','01'],['review','관리자 확인',closure.blockers.length||'✓'],['history','검증 이력',ledger.length]].map(([id,label,num])=><button key={id} className={view===id?'nav-active':''} aria-current={view===id?'page':undefined} onClick={()=>setView(id)}>{label}<span>{num}</span></button>)}</nav><div className="sidebar-caption">수사했다는 기록이 아니라,<br/>수사했다는 증거.</div><div className="sidebar-bottom"><span className="avatar">A</span><div>시연 담당자<small>AIF4 · 데모 워크스페이스</small></div></div></aside>
 <main id="main-content"><header className="topbar"><span>워크스페이스 <i>/</i> {{case:'사건 검증',review:'관리자 확인',history:'검증 이력'}[view]}</span><span className="demo-label">DEMO · 가상 사건</span></header><div className="content"><div className="page-heading"><div><div className="eyebrow">CHAIN OF INVESTIGATION</div><h1>{view==='case'?'기록을 넘어, 수행을 확인하다.':view==='review'?'확인이 필요한 순간, 판단은 사람에게.':'검증의 근거를 따라가다.'}</h1><p>{view==='case'?'담당자의 기록과 원천기관의 증거를 한눈에 대조합니다.':view==='review'?'미확인 수사 단계를 검토하고, 다음 조치를 기록합니다.':'검증 결과와 관리자 확인을 시간 순서로 확인합니다.'}</p></div><button className="secondary" disabled={busy} onClick={()=>reset()}>시연 초기화 ↻</button></div>
 <div className="scenario-row" aria-label="시연 시나리오">{SCENARIOS.map((s,i)=><button key={s.id} disabled={busy} aria-pressed={scenario===s.id} className={'scenario '+(scenario===s.id?'selected':'')} onClick={()=>reset(s.id)}><span className="scenario-index">0{i+1}</span><span>{s.title}<small>{s.desc}</small></span><span className="radio"/></button>)}</div>
 <section className="case-banner"><div><span className="eyebrow">MISSING PERSON / FP-DEMO-001</span><h2>한빛동 실종 신고</h2><p>대상자 P-1872 <span>접수 2026.09.13 18:00</span></p></div><div className="case-progress"><span className={'status '+(closed?'verified':'pending')}>{closed?'관리자 확인 · 종결':'수사 진행 중'}</span><div><b>{count}</b><span> / 5 단계 검증 일치</span></div><div className="progress-track"><span style={{width:`${count*20}%`}}/></div></div></section>
 {notice&&<div className="notice-line" role="status">{notice}</div>}
 {view==='case'&&<><div className="main-grid"><div><section className="panel steps-panel"><div className="panel-title"><h2>수사 절차</h2><span>5 STEPS</span></div>{steps.map(s=><button key={s.id} className={'step '+(selected===s.id?'active':'')} aria-pressed={selected===s.id} onClick={()=>setSelected(s.id)}><span className="step-number">{String(s.id).padStart(2,'0')}</span><div><strong>{s.name}</strong><small className={STATUS[results[s.id]?.status]?.tone}>{STATUS[results[s.id]?.status]?.label??'검증 대기'}</small></div><span>›</span></button>)}</section><button className="secondary all-verify" disabled={busy||closed} onClick={()=>run(true)}>{busy?'검증 중…':'전체 5단계 검증'}</button><div className="reference-clock">시연 기준 시각<br/><b>2026.09.13 19:00 (KST)</b></div></div>
 <section className="panel detail-panel"><div className="panel-title"><div><span className="eyebrow">STEP {String(selected).padStart(2,'0')} · 필수 절차</span><h2>{step.name}</h2></div><Badge status={result?.status}/></div><div className="compare-grid"><div className="record"><div className="record-label">CLAIM <span>담당자 기록</span></div><label className="field-label" htmlFor="claim-raw">수행 기록 · 메모</label><textarea id="claim-raw" disabled={busy||closed} value={step.claim.raw} onChange={e=>edit('raw',e.target.value)} placeholder="수사 수행 내용을 입력하세요."/>
 <label className="meta-row"><span>대상자·증거 ID</span><input aria-label="대상자·증거 ID" disabled={busy||closed} value={step.claim.target} onChange={e=>edit('target',e.target.value)} maxLength={40}/></label><label className="meta-row"><span>행위 유형</span><select aria-label="행위 유형" disabled={busy||closed} value={step.claim.action} onChange={e=>edit('action',e.target.value)}>{Object.entries(ACTIONS).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="meta-row"><span>수행 시각</span><input type="time" aria-label="수행 시각" disabled={busy||closed} value={step.claim.time} onChange={e=>edit('time',e.target.value)}/></label><label className="meta-row"><span>수행 결과</span><select aria-label="수행 결과" disabled={busy||closed} value={step.claim.success?'success':'fail'} onChange={e=>edit('success',e.target.value==='success')}><option value="success">완료</option><option value="fail">미완료</option></select></label></div>
 <div className="record"><div className="record-label">PROOF <span>가상 기관 기록</span></div><h3>{step.source}</h3><div className={'proof-note '+(step.proof.kind!=='record'?'proof-missing':'')}><strong>{step.proof.kind==='no_record'?'조회 결과 · 발신 기록 없음':step.proof.kind==='no_response'?'확보 응답 없음':step.id===5?'보존정책 메타데이터 확인':step.id===4?'CCTV 영상 3건 · 확보 완료':'기관 기록 1건 · 수행 성공'}</strong><small>{step.proof.kind==='no_record'?'조회 기간 내 대상자에 대한 통화기록 0건':step.proof.kind==='no_response'?'관제센터에 확보 요청이 필요합니다.':'독립된 예시 데이터와 입력값을 대조합니다.'}</small></div><div className="meta-row"><span>대상자·증거 ID</span><b>{step.proof.target}</b></div><div className="meta-row"><span>행위 유형</span><b>{ACTIONS[step.proof.action]}</b></div><div className="meta-row"><span>기록 시각</span><b>{step.proof.kind==='record'?step.proof.time:'—'}</b></div><div className="meta-row"><span>발행기관</span><b className="mono">{step.proof.issuer}</b></div></div></div>
 {selected>=4&&<div className={'deadline-strip '+(!step.acquired?'urgent':'')}><span>◷ 보존기한</span><strong>{prettyTime(step.deadline)}</strong><span>{step.acquired?'관련 증거 확보 완료':'잔여 12시간 · CCTV 3건 미확보'}</span></div>}
 <div className="verify-footer"><span>입력한 대상·행위·시각·완료 여부를 대조합니다.<br/>자연어 메모의 의미 판단은 연결 전입니다.</span><button className="primary" disabled={busy||closed} onClick={()=>run(false)}>{busy?'검증 중…':result?'다시 검증하기 ↻':'기록 검증하기 →'}</button></div>
 {result&&<div className={'result-area '+STATUS[result.status].tone} aria-live="polite"><div className="result-heading"><Badge status={result.status}/><span className="eyebrow">VERIFICATION RESULT</span></div><p>{result.reason}</p><div className="check-list">{result.checks.map((c,i)=><div key={i}><span className={c.ok?'check-pass':'check-fail'}>{c.ok?'✓':'!'}</span><strong>{c.name}</strong><span>{c.detail}</span></div>)}</div><button className="text-button" onClick={()=>setView('history')}>검증 기록과 해시 확인 ↗</button></div>}</section></div><div className="next-action"><div><h3>{closure.allowed?'필수 단계 검증을 마쳤습니다.':`확인이 필요한 단계가 ${closure.blockers.length}개 있습니다.`}</h3><p>사건 종결은 관리자 최종 확인 후 진행됩니다.</p></div><button className="secondary" onClick={()=>setView('review')}>관리자 확인으로 →</button></div></>}
 {view==='review'&&<section className="panel review-panel"><div className="panel-title"><div><span className="eyebrow">HUMAN IN THE LOOP</span><h2>{closed?'관리자 최종 확인 완료':closure.allowed?'종결 검토 가능':'현재 종결할 수 없습니다'}</h2></div><span className={'status '+(closed||closure.allowed?'verified':'mismatch')}>{closed?'종결 완료':closure.allowed?'5 / 5 검증 일치':`${closure.blockers.length}개 단계 확인 필요`}</span></div><div className="review-body"><p>{closed?'관리자 확인 사유가 이 세션의 기록에 남았습니다. 다른 시나리오는 상단에서 시작할 수 있습니다.':closure.allowed?'필수 단계의 검증 결과를 확인했습니다. 최종 판단과 확인 사유를 남겨 주세요.':'미검증·불일치·기한 위험이 있는 단계는 관리자 확인 사유만 입력해도 검증 완료로 바뀌지 않습니다.'}</p><div className="review-steps">{(closure.allowed?steps:closure.blockers).map(s=><button key={s.id} onClick={()=>{setSelected(s.id);setView('case')}}><span className="step-number">0{s.id}</span><strong>{s.name}</strong><Badge status={results[s.id]?.status}/><span>↗</span></button>)}</div><label htmlFor="review-reason" className="field-label">관리자 확인 사유 <span>필수</span></label><textarea id="review-reason" value={reason} disabled={busy||closed} onChange={e=>{setReason(e.target.value);setReviewed(false)}} placeholder={closure.allowed?'예: 필수 수사 단계의 증거와 검증 결과를 확인하였으며 종결 검토를 완료했습니다.':'예: 실종자 본인 연락을 재수행하고, 통신사 기록을 다시 요청합니다.'} maxLength={2000}/><div className="review-actions">{!closed&&<><button className="secondary" disabled={busy||!reason.trim()||reviewed} onClick={()=>saveReview(false)}>{reviewed?'확인 기록 저장됨':'확인 사유 및 보완 요청 저장'}</button><button className="primary" disabled={busy||!reason.trim()||!closure.allowed} onClick={()=>setConfirm(true)}>최종 종결 승인</button></>}</div><small className="subtle">실제 사건에 영향을 주지 않는 시연입니다. 기록은 현재 브라우저 세션에서만 유지됩니다.</small></div></section>}
 {view==='history'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">SESSION RECORDS · ON-CHAIN 미연결</span><h2>검증 및 관리자 확인 이력</h2></div><button className="secondary" disabled={!ledger.length} onClick={download}>기록 내려받기 ↓</button></div>{ledger.length===0?<div className="empty-state"><span>⌁</span><h3>아직 검증 기록이 없습니다.</h3><p>사건 검증에서 기록을 대조하면 결과와 해시가 이곳에 남습니다.</p><button className="primary" onClick={()=>setView('case')}>사건 검증으로</button></div>:<div className="ledger-list">{[...ledger].reverse().map((entry,i)=><article key={entry.hash} className="ledger-entry"><div className="ledger-number">{String(ledger.length-i).padStart(2,'0')}</div><div><div className="ledger-title"><h3>{entry.type==='verification'?`STEP 0${entry.step_id} · ${entry.step_name}`:entry.type==='closure'?'관리자 최종 종결':'관리자 확인 · 보완 요청'}</h3>{entry.result&&<Badge status={entry.result.status}/>}</div><p>{entry.result?.reason??entry.reason}</p><div className="hash-row"><span>SHA-256</span><code>{entry.hash}</code></div><small>{prettyTime(entry.recorded_at)} · 브라우저 세션 기록 · 블록체인 거래 아님</small></div></article>)}</div>}</section>}
 <div className="scope-note"><b>시연 범위</b>{import.meta.env.VITE_VERIFICATION_API?'로컬 서버':'브라우저'}에서 규칙을 실행합니다. 모든 사건·기관 데이터는 가상입니다. AI 모델·기관 전자서명·블록체인은 미연결이며, 새로고침·시연 전환 시 기록이 초기화됩니다.</div></div></main>
 {confirm&&<div className="modal-backdrop" onKeyDown={e=>{if(e.key==='Escape')setConfirm(false)}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><div className="eyebrow">FINAL REVIEW</div><h2 id="confirm-title">시연 사건을 종결할까요?</h2><p>필수 5개 단계의 검증 결과와 아래 확인 사유를 기록합니다.</p><blockquote>{reason}</blockquote><div className="review-actions"><button className="secondary" autoFocus onClick={()=>setConfirm(false)}>돌아가기</button><button className="primary" disabled={busy} onClick={()=>saveReview(true)}>확인 후 종결</button></div></div></div>}
 </div>
}
