import React, {useEffect, useRef, useState} from 'react';
import {flushSync} from 'react-dom';
import {ACTIONS, STATUS, SCENARIOS, DEMO_TIME, createSteps, verifyStep, closureState, makeLedgerEntry} from './engine.js';
import {issueProof, validateProof} from './proofs.js';

const demoSteps = id => createSteps(id).map(s => !s.claim.raw ? {...s, claim:{...s.claim, raw:'CCTV 영상은 아직 확보하지 못했습니다. 관제센터의 응답을 기다리고 있습니다.'}} : s);
const phases = ['사건 접수', 'Claim 입력', '기관 Proof 발행', 'AI + Rule 검증', '기록 · 관리자 확인'];
const roles = ['담당자', '담당자', '원천기관', '검증 시스템', '관리자'];
const pretty = t => new Date(t).toLocaleString('ko-KR', {timeZone:'Asia/Seoul', month:'2-digit', day:'2-digit', hour:'2-digit', minute:'2-digit', hour12:false});
function Badge({status}) { const s=STATUS[status]??STATUS.PENDING; return <span className={'badge '+s.tone}>{s.label}</span>; }
function Facts({proof}) { return <dl className="facts"><div><dt>대상자·증거 ID</dt><dd>{proof.target}</dd></div><div><dt>행위 유형</dt><dd>{ACTIONS[proof.action]}</dd></div><div><dt>수행 시각</dt><dd>{!proof.kind||proof.kind==='record'?proof.time:'해당 기록 없음'}</dd></div>{proof.issuer&&<div><dt>발행기관</dt><dd>{proof.issuer}</dd></div>}</dl>; }
const proofText = s => s.proof.kind==='no_record'?'조회 기간 내 해당 대상자에 대한 발신 기록 0건':s.proof.kind==='no_response'?'관제센터 응답 대기 · CCTV 미확보':`${s.proof.target} · ${ACTIONS[s.proof.action]} · ${s.proof.time} 수행 성공`;

export default function FlowApp() {
  const [phase,setPhase]=useState(0), [scenario,setScenario]=useState('normal'), [steps,setSteps]=useState(()=>demoSteps()), [selected,setSelected]=useState(1);
  const [title,setTitle]=useState('한빛동 실종 신고'), [summary,setSummary]=useState('한빛동에서 실종 신고가 접수되었습니다. 본인 연락, 최근 위치와 마지막 목격지 주변 CCTV 확인이 필요합니다.');
  const [accepted,setAccepted]=useState(false), [saved,setSaved]=useState({}), [receipts,setReceipts]=useState({}), [results,setResults]=useState({}), [ledger,setLedger]=useState([]);
  const [busy,setBusy]=useState(false), [notice,setNotice]=useState(''), [reason,setReason]=useState(''), [closed,setClosed]=useState(false), [confirm,setConfirm]=useState(false), [about,setAbout]=useState(false), [tab,setTab]=useState('review');
  const keys=useRef({}), lock=useRef(false), dialog=useRef(null), state=useRef({});
  const step=steps.find(s=>s.id===selected), receipt=receipts[selected], result=results[selected];
  const closure=closureState(steps,results), verified=Object.values(results).filter(r=>r.completed).length;
  const completed=[accepted,Object.keys(saved).length===5,Object.keys(receipts).length===5,Object.keys(results).length===5,closed];
  function reset(id=scenario) { if(lock.current)return; setScenario(id);setSteps(demoSteps(id));setSelected(id==='deadline'?4:1);setPhase(0);setTab('review');setAbout(false);setAccepted(false);setSaved({});setReceipts({});setResults({});setLedger([]);setReason('');setClosed(false);setConfirm(false);keys.current={};setNotice('새 가상 사건을 준비했습니다. 사건을 접수해 주세요.'); }
  function edit(field,value) { setSteps(a=>a.map(s=>s.id===selected?{...s,claim:{...s.claim,[field]:value}}:s));setSaved(a=>{const n={...a};delete n[selected];return n});setResults(a=>{const n={...a};delete n[selected];return n});setNotice('Claim이 변경되었습니다. 저장 후 다시 검증해 주세요.'); }
  function saveClaims(all=false) { const targets=all?steps:[step];if(targets.some(s=>!s.claim.raw.trim()||!s.claim.target.trim()||!s.claim.time)){setNotice('수행 기록·대상 ID·시각을 입력해 주세요. 미확보 사실도 기록할 수 있습니다.');return;}setSaved(a=>({...a,...Object.fromEntries(targets.map(s=>[s.id,true]))}));setNotice(all?'5개 Claim을 저장했습니다. 원천기관 화면에서 별도의 증빙을 발행해 주세요.':'담당자 Claim을 저장했습니다.'); }
  async function issue(all=false) { if(lock.current||closed)return;lock.current=true;setBusy(true);try{const next={...receipts};for(const s of all?steps:[step])next[s.id]=await issueProof(s,keys.current);setReceipts(next);setResults(a=>{const n={...a};for(const s of all?steps:[step])delete n[s.id];return n});setNotice('가상 기관의 자체 기록을 처리했습니다. 응답 대기는 증빙 발행과 구분합니다.');}catch{setNotice('증빙을 발행하지 못했습니다. 다시 시도해 주세요.');}finally{lock.current=false;setBusy(false);} }
  async function run(all=false) {
    if(lock.current||closed)return;lock.current=true;setBusy(true);
    try {
      const targets=all?steps:[step];if(targets.some(s=>!saved[s.id]||!receipts[s.id])){setNotice('먼저 담당자 Claim을 저장하고 원천기관의 응답을 처리해 주세요.');return;}
      const next={...results}, entries=[];let previous=ledger.at(-1)?.hash??null;
      for(const s of targets) {
        const r=receipts[s.id]; let answer;
        if(!r.pending && !(await validateProof(r,s,keys.current))) answer={status:'MISMATCH',reason:'발행기관의 시연 서명 또는 증빙 무결성을 확인할 수 없습니다.',checks:[],completed:false};
        else {
          const checked={...s,proof:r.pending?s.proof:r.payload};
          if(import.meta.env.VITE_VERIFICATION_API){const response=await fetch(import.meta.env.VITE_VERIFICATION_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({step:checked,now:DEMO_TIME}),signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error('검증 서버 연결을 확인해 주세요.');answer=await response.json();if(!STATUS[answer.status]||!Array.isArray(answer.checks))throw new Error('검증 응답 형식이 올바르지 않습니다.');}
          else answer=verifyStep(checked);
          answer={...answer,semantic_status:'NOT_CONNECTED',checks:[{name:'기관 시연 서명',ok:!r.pending,detail:r.pending?'기관 응답 대기':'브라우저 시연키 · 서명 및 해시 검증'},...answer.checks]};
        }
        next[s.id]=answer;
        const entry=await makeLedgerEntry({type:'verification',step_id:s.id,step_name:s.name,proof_hash:r.hash??null,issuer:s.issuer,issuer_signature:r.signature??null,result:answer},previous);previous=entry.hash;entries.push(entry);
      }
      setResults(next);setLedger(a=>[...a,...entries]);setNotice('규칙 검증을 마쳤습니다. AI 의미 대조는 연결 전이며 아래 결과에 포함되지 않습니다.');
    } catch(e) {setNotice(e.message||'검증에 실패했습니다. 다시 시도해 주세요.');} finally {lock.current=false;setBusy(false);}
  }
  async function review(close=false) { if(lock.current||closed||!reason.trim()||(close&&!closure.allowed))return;lock.current=true;setBusy(true);try{const entry=await makeLedgerEntry({type:close?'closure':'review',reviewer:'시연 관리자',reason:reason.trim(),decision:close?'CLOSED':'FOLLOW_UP_REQUIRED',blockers:closure.blockers.map(s=>s.id)},ledger.at(-1)?.hash??null);setLedger(a=>[...a,entry]);setConfirm(false);if(close)setClosed(true);setNotice(close?'관리자가 시연 사건의 최종 확인을 완료했습니다.':'보완 요청과 확인 사유를 저장했습니다.');}catch{setNotice('확인 기록 저장에 실패했습니다.');}finally{lock.current=false;setBusy(false);} }
  function download() {const blob=new Blob([JSON.stringify({project:'FullProof',demo:true,case:{title,summary},scenario,reference_time:DEMO_TIME,closed,on_chain:false,ledger,off_chain_demo:steps.map(s=>({step_id:s.id,claim:s.claim,proof:receipts[s.id]??null}))},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='fullproof-demo-records.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  state.current={scenario,phase,selected,accepted,saved,results,closed};
  useEffect(()=>{const ctx=document.modelContext;if(!ctx?.registerTool)return;const life=new AbortController();const list=[{name:'fullproof_read_demo',description:'Read the simulated case workflow and verification results.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>state.current},{name:'fullproof_start_scenario',description:'Reset temporary demo records and open case intake for a scenario.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:['normal','mismatch','deadline']}},required:['scenario'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||Object.keys(input).length!==1||!SCENARIOS.some(s=>s.id===input.scenario)||lock.current)throw new Error('Invalid scenario or busy');flushSync(()=>reset(input.scenario));return state.current}}];for(const t of list)try{Promise.resolve(ctx.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);
  useEffect(()=>{if(!confirm)return;const previous=document.activeElement;dialog.current?.showModal();return()=>{dialog.current?.close();previous?.focus();};},[confirm]);
  const chooseStep=<aside className="task-list"><p className="eyebrow">실종사건 수사절차</p>{steps.map(s=><button key={s.id} className={selected===s.id?'selected':''} aria-pressed={selected===s.id} onClick={()=>setSelected(s.id)}><span className="task-number">0{s.id}</span><span>{s.name}<small>{phase===1?saved[s.id]?'Claim 저장됨':'입력 대기':phase===2?receipts[s.id]?.pending?'기관 응답 대기':receipts[s.id]?'Proof 발행됨':'발행 전':STATUS[results[s.id]?.status]?.label??'검증 대기'}</small></span><span>›</span></button>)}<p className="small-note">시연 기준 시각<br/>2026.09.13 19:00 KST</p></aside>;
  return <div className="app"><a className="skip-link" href="#content">본문으로 이동</a>
    <header className="masthead"><button className="brand" onClick={()=>setAbout(!about)} aria-label="FullProof 프로젝트 소개"><img className="brand-symbol" src={import.meta.env.BASE_URL+'logo.svg'} alt="" width="64" height="64"/><span>FULLPROOF<small>AI·블록체인 기반 수사행위 검증 플랫폼</small></span></button><div className="header-right"><button onClick={()=>setAbout(!about)}>{about?'시연 화면으로 →':'프로젝트 소개 ↗'}</button><span className="team">BLOCK AI 26 · TRACK 1<br/>AIF4</span></div></header>
    <div className="tape" aria-hidden="true">POLICE LINE　　✳　　POLICE LINE　　✳　　POLICE LINE　　✳　　POLICE LINE　　✳　　POLICE LINE</div>
    <main id="content">{about?<section className="about"><img src={import.meta.env.BASE_URL+'presentation-cover.png'} alt="FullProof 온전한 증명. 수사했다는 기록을, 확인 가능한 증명으로. AIF4 배소현 신민주 박지수 박다연."/><div className="paper about-body"><h2>증거 관리에서 수사행위 검증으로</h2><p>핵심 질문은 ‘기록한 수사행위에 실제 수행 근거가 있는가?’입니다. 담당자의 Claim과 원천기관의 Proof를 교차 확인하고, 증빙 부재·불일치·보존기한 위험을 관리자에게 알립니다.</p><div className="principles"><article><h3>01 수행자와 발행자 분리</h3><p>담당자는 수행 기록을 입력하고, 원천기관은 자체 기록에 서명하여 Proof를 발행합니다.</p></article><article><h3>02 AI·규칙·기록의 역할 구분</h3><p>AI는 의미 대조, 규칙은 사실 조건 검증, 블록체인은 검증 이력의 추적을 담당합니다.</p></article><article><h3>03 최종 판단은 사람에게</h3><p>AI는 범죄 혐의나 사건 종결을 판단하지 않습니다. 보완 요청과 최종 확인은 사람이 수행합니다.</p></article></div><button className="primary" onClick={()=>setAbout(false)}>5단계 시연으로 돌아가기 →</button></div></section>:<>
    <div className="intro"><div><p className="eyebrow">기록과 사실 사이를 잇다</p><h1>수사했다는 기록을,<br/>확인 가능한 증명으로.</h1></div><div className="intro-side"><p>담당자의 수행 기록과 원천기관의 증빙을<br/>연결하는 5단계 검증 절차</p><button className="quiet" disabled={busy} onClick={()=>reset()}>시연 초기화 ↻</button></div></div>
    <div className="scenario-bar"><span>시연 시나리오</span>{SCENARIOS.map((s,i)=><button key={s.id} disabled={busy} aria-pressed={scenario===s.id} className={scenario===s.id?'selected':''} onClick={()=>reset(s.id)}><span>0{i+1}</span>{s.title}</button>)}<span className="demo-stamp">가상 데이터</span></div>
    <nav className="phases" aria-label="서비스 진행 단계">{phases.map((p,i)=><button key={p} disabled={busy||(!accepted&&i>0)} aria-current={phase===i?'step':undefined} className={phase===i?'active':completed[i]?'done':''} onClick={()=>setPhase(i)}><span>Step {i+1}{completed[i]&&<i>✓</i>}</span>{p}</button>)}</nav>
    {notice&&<div className="notice" role="status">{notice}</div>}
    <section className="paper"><div className="section-title"><div><p className="eyebrow">STEP {phase+1} · {roles[phase]}</p><h2>{['사건 접수 · 절차 템플릿 적용','담당자 수행 → Claim 입력','원천기관의 Proof 발행','AI + Rule Engine 교차검증','검증 기록 → 관리자 확인'][phase]}</h2></div><span className="tag">{phase===0?'사전 정의된 실종사건 템플릿':closed?'관리자 최종 확인 완료':title}</span></div>
    {phase===0&&<div className="intake-grid"><form onSubmit={e=>{e.preventDefault();setAccepted(true);setPhase(1);setNotice('사건을 접수하고 실종사건 템플릿을 적용했습니다. 담당자 Claim을 입력해 주세요.');}}><label>사건명<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={80} disabled={accepted}/></label><label>사건 요약<textarea value={summary} onChange={e=>setSummary(e.target.value)} required maxLength={2000} disabled={accepted}/></label><p className="small-note">개인정보를 입력하지 마세요. 현재 시연은 준비된 실종사건 템플릿을 적용하며, AI 자동 추천은 연결 전입니다.</p><button className="primary">{accepted?'담당자 Claim 입력으로 →':'사건 접수 및 템플릿 적용 →'}</button></form><aside className="template"><p className="eyebrow">사전 정의된 수사절차</p><h3>실종사건 · STEP 01–05</h3><ol>{steps.map(s=><li key={s.id}>{s.name}</li>)}</ol><p>AI는 절차를 창작하지 않고, 정의된 템플릿 중 필요한 STEP을 추천합니다.</p></aside></div>}
    {phase>0&&phase<4&&<div className="work-grid">{chooseStep}<div className="work-detail"><div className="detail-title"><div><span className="eyebrow">수사절차 STEP 0{step.id}</span><h3>{step.name}</h3></div>{phase===3?<Badge status={result?.status}/>:<span className="role-label">{phase===1?'담당자 작업':'원천기관 작업 · 모의 연동'}</span>}</div>
    {phase===1&&<><p className="instruction">수사 수행 내용을 기록해 주세요. 기관 증빙은 다음 단계에서 별도로 발행됩니다.</p><label>수행 기록 · Claim<textarea value={step.claim.raw} disabled={busy||closed} onChange={e=>edit('raw',e.target.value)} placeholder="예: 아직 CCTV 영상을 확보하지 못했습니다."/></label><div className="fields"><label>대상자·증거 ID<input value={step.claim.target} onChange={e=>edit('target',e.target.value)} disabled={busy||closed} maxLength={40}/></label><label>행위 유형<select value={step.claim.action} onChange={e=>edit('action',e.target.value)} disabled={busy||closed}>{Object.entries(ACTIONS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>수행 시각<input type="time" value={step.claim.time} onChange={e=>edit('time',e.target.value)} disabled={busy||closed}/></label><label>수행 결과<select value={step.claim.success?'success':'fail'} onChange={e=>edit('success',e.target.value==='success')} disabled={busy||closed}><option value="success">완료</option><option value="fail">미완료</option></select></label></div><div className="actions"><button className="primary" disabled={busy||closed} onClick={()=>saveClaims()}>이 Claim 저장</button><button className="secondary" disabled={busy||closed} onClick={()=>saveClaims(true)}>예시 Claim 5개 저장</button><span>{Object.keys(saved).length} / 5 저장</span></div></>}
    {phase===2&&<><div className="source-banner"><span className="source-icon">{step.issuer==='MOCK-TELECOM'?'T':'C'}</span><div><h3>{step.issuer==='MOCK-TELECOM'?'Mock 통신사':'Mock CCTV 관제센터'}</h3><p>Source Authority · {step.issuer}</p></div></div><p className="instruction">기관의 자체 조회 결과입니다. 담당자의 Claim을 복사하여 만들지 않습니다.</p><div className={'proof-box '+(step.proof.kind!=='record'?'missing':'')}><span className="eyebrow">기관 자체 기록</span><h3>{proofText(step)}</h3><Facts proof={step.proof}/></div>{receipt&&<div className="receipt"><strong>{receipt.pending?'기관 응답 대기 · Proof 미발행':'Proof 발행 · 시연 서명 완료'}</strong>{receipt.hash&&<><p className="hash">Proof SHA-256　{receipt.hash}</p><details><summary>기관 시연 서명 확인</summary><p className="hash">{receipt.signature}</p></details></>}</div>}<div className="actions"><button className="primary" disabled={busy||closed} onClick={()=>issue()}>{busy?'처리 중…':'이 기관 응답 처리'}</button><button className="secondary" disabled={busy||closed} onClick={()=>issue(true)}>전체 기관 응답 처리</button></div><p className="small-note">전자서명은 현재 브라우저에서 생성한 기관별 시연키로 실제 계산합니다. 기관 인증·Wallet 연동은 연결 전이며, 새로고침하면 키가 초기화됩니다.</p></>}
    {phase===3&&<><div className="compare"><article><span className="eyebrow">CLAIM · 담당자</span><h3>{step.claim.raw||'수행 기록 없음'}</h3><Facts proof={step.claim}/><span className="small-note">{saved[selected]?'담당자 저장 완료':'Claim 저장 필요'}</span></article><article><span className="eyebrow">PROOF · 원천기관</span><h3>{receipt?proofText(step):'발행된 증빙이 없습니다.'}</h3>{receipt&&!receipt.pending&&<Facts proof={receipt.payload}/>}<span className="small-note">{receipt?.pending?'기관 응답 대기':receipt?'기관 시연 서명 첨부':'기관 화면에서 응답을 처리해 주세요.'}</span></article></div><div className="engine-row"><article><span className="engine-number">01</span><div><h3>AI · 표현의 의미 대조</h3><p>Claim 문장과 Proof 메타데이터가 같은 행위인지 비교</p></div><span className="badge pending">모델 연결 전</span></article><article><span className="engine-number">02</span><div><h3>Rule Engine · 사실 조건 검증</h3><p>대상자 ID · 시각 · 기관 · 행위 유형 · 수행 완료</p></div><span className="badge verified">실행 가능</span></article></div>{selected>=4&&<div className={'deadline '+(!step.acquired?'urgent':'')}><strong>CCTV 보존기한 {pretty(step.deadline)}</strong><span>{step.acquired?'관련 증거 확보 완료':'잔여 12시간 · CCTV 3건 미확보'}</span></div>}<div className="actions"><button className="primary" disabled={busy||closed||!saved[selected]||!receipt} onClick={()=>run()}>{busy?'검증 중…':'이 STEP 규칙 검증'}</button><button className="secondary" disabled={busy||closed||Object.keys(saved).length!==5||Object.keys(receipts).length!==5} onClick={()=>run(true)}>전체 5개 규칙 검증</button></div>{result&&<div className={'result '+STATUS[result.status].tone} aria-live="polite"><Badge status={result.status}/><h3>{result.reason}</h3><div className="checks">{result.checks.map((c,i)=><div key={i}><span className={c.ok?'pass':'fail'}>{c.ok?'✓':'!'}</span><strong>{c.name}</strong><span>{c.detail}</span></div>)}</div><p className="small-note">위 결과는 기관 시연 서명과 규칙 검증의 결과입니다. AI 의미 대조 결과는 포함하지 않습니다.</p></div>}</>}
    </div></div>}
    {phase===4&&<div className="final-body"><div className="summary-grid"><div><span>규칙 검증 일치</span><strong>{verified}<small> / 5</small></strong></div><div><span>관리자 확인 필요</span><strong>{closure.blockers.length}<small>개 STEP</small></strong></div><div><span>블록체인 연결</span><strong className="not-connected">미연결</strong></div></div><div className="tabs" role="tablist" aria-label="관리자 화면"><button role="tab" aria-selected={tab==='review'} onClick={()=>setTab('review')}>관리자 확인</button><button role="tab" aria-selected={tab==='history'} onClick={()=>setTab('history')}>검증 이력 ({ledger.length})</button><button role="tab" aria-selected={tab==='storage'} onClick={()=>setTab('storage')}>온체인 · 오프체인</button></div>
    {tab==='review'&&<div role="tabpanel"><div className="human-note"><strong>최종 판단은 사람이 합니다.</strong><p>AI는 범죄 혐의나 사건 종결을 직접 판단하지 않으며, 이상징후 탐지와 경고 역할만 수행합니다.</p></div><h3>{closed?'관리자 최종 확인 완료':closure.allowed?'필수 STEP 규칙 검증 완료 · 관리자 검토 가능':'우선 확인이 필요한 항목'}</h3><div className="review-list">{[...(closure.allowed?steps:closure.blockers)].sort((a,b)=>(['EXPIRED','EXPIRING_SOON'].includes(results[b.id]?.status)?10:0)-(['EXPIRED','EXPIRING_SOON'].includes(results[a.id]?.status)?10:0)).map(s=><button key={s.id} onClick={()=>{setSelected(s.id);setPhase(3);}}><span className="task-number">0{s.id}</span><div><strong>{s.name}</strong><p>{results[s.id]?.reason??'아직 검증하지 않았습니다.'}</p></div><Badge status={results[s.id]?.status}/><span>↗</span></button>)}</div><label>관리자 확인 사유 · 보완 요청<textarea value={reason} onChange={e=>setReason(e.target.value)} disabled={busy||closed} maxLength={2000} placeholder="검토한 근거와 추가로 확인하거나 보완할 내용을 기록해 주세요."/></label><div className="actions"><button className="secondary" disabled={busy||closed||!reason.trim()} onClick={()=>review()}>확인 사유 · 보완 요청 저장</button><button className="primary" disabled={busy||closed||!reason.trim()||!closure.allowed} onClick={()=>setConfirm(true)}>{closed?'최종 확인 완료':'관리자 최종 확인'}</button></div><p className="small-note">보완 요청을 저장해도 불일치는 해소되지 않습니다. 시연의 최종 확인은 5개 STEP 규칙 검증 후 가능합니다. AI 및 온체인 연결을 완료한 운영 승인과는 구분됩니다.</p></div>}
    {tab==='history'&&<div role="tabpanel"><div className="history-heading"><p>판정 결과 · Proof 해시 · 기관 서명 · 시각 · 관리자 확인 이력</p><button className="secondary" disabled={!ledger.length} onClick={download}>시연 기록 내려받기 ↓</button></div><div className="connection-note">현재는 브라우저 세션에 해시를 연결하여 기록합니다. 블록체인 거래는 아직 발생하지 않습니다.</div>{!ledger.length?<p className="empty">아직 검증 기록이 없습니다. Step 4에서 규칙 검증을 실행해 주세요.</p>:[...ledger].reverse().map((entry,i)=><article className="ledger-entry" key={entry.hash}><div className="ledger-title"><span className="task-number">{ledger.length-i}</span><h3>{entry.type==='verification'?`STEP 0${entry.step_id} · ${entry.step_name}`:entry.type==='closure'?'관리자 최종 확인':'관리자 확인 · 보완 요청'}</h3>{entry.result&&<Badge status={entry.result.status}/>}</div><p>{entry.result?.reason??entry.reason}</p>{entry.proof_hash&&<p className="hash">Proof 해시　{entry.proof_hash}</p>}<details><summary>기록 해시 · 기관 서명 보기</summary><p className="hash">기록 SHA-256　{entry.hash}</p><p className="hash">이전 기록　{entry.previous_hash??'첫 기록'}</p><p className="hash">기관 서명　{entry.issuer_signature??'해당 없음'}</p></details><small>{pretty(entry.recorded_at)} · {entry.issuer??'시연 관리자'} · 세션 기록</small></article>)}</div>}
    {tab==='storage'&&<div className="storage-grid" role="tabpanel"><article><span className="eyebrow">ON-CHAIN · 기획상 기록 대상</span><h3>검증 정보</h3><ul><li>Proof 해시</li><li>기관 ID · 전자서명 · 타임스탬프</li><li>절차 ID · 검증 결과</li><li>관리자 확인 이력</li></ul><p>현재: 세션 해시 기록<br/>연결 예정: Role Registry · Proof Registry · Verification Event</p></article><article><span className="eyebrow">OFF-CHAIN · 기획상 보관 대상</span><h3>암호화된 원본</h3><ul><li>통화기록 · 위치정보</li><li>CCTV 영상</li><li>사건기록 · 개인정보</li></ul><p>현재: 가상 메타데이터만 사용<br/>연결 예정: 암호화 저장소 · PostgreSQL</p></article><p className="storage-limit">블록체인은 원본 사실의 진실성 자체를 보장하지 않습니다. 누가 무엇을 언제 증명했는지 확인할 수 있도록 검증 이력을 남기는 역할입니다.</p></div>}
    </div>}
    </section>
    <div className="flow-footer"><span>{phase===0?'AI는 정의된 템플릿에서 추천합니다.':phase===1?'담당자의 주장과 기관의 증빙을 분리합니다.':phase===2?'원천기관이 자신의 기록을 발행합니다.':phase===3?'의미 대조와 사실 조건 검증을 구분합니다.':'이상징후를 먼저 확인하고, 최종 판단은 사람이 합니다.'}</span><div>{phase>0&&<button className="secondary" disabled={busy} onClick={()=>setPhase(phase-1)}>← 이전 단계</button>}{phase>0&&phase<4&&<button className="primary" disabled={busy} onClick={()=>setPhase(phase+1)}>{phases[phase+1]} →</button>}</div></div>
    </>}
    <footer className="site-footer"><strong>FULLPROOF <span>온전한 증명</span></strong><p>AIF4 · 배소현 신민주 박지수 박다연</p><details><summary>시연 구현 범위 및 데이터 안내</summary><p>가상 사건과 기관으로 서비스 5단계를 시연합니다. 규칙 검증·기관별 브라우저 시연키 서명·SHA-256 기록은 실제 실행됩니다. AI 추천·의미 대조, 기관 인증·Wallet, 실제 블록체인, 암호화 원본 저장소는 연결 전입니다. 데이터와 시연키는 새로고침 또는 시나리오 전환 시 초기화됩니다.</p></details></footer>
    </main>{confirm&&<dialog ref={dialog} aria-labelledby="confirm-heading" className="confirm-dialog" onCancel={()=>setConfirm(false)} onClose={()=>setConfirm(false)}><p className="eyebrow">관리자 최종 판단</p><h2 id="confirm-heading">시연 사건의 확인을 완료할까요?</h2><p>규칙 검증 결과와 아래 확인 사유를 기록합니다. 실제 사건에 영향을 주지 않습니다.</p><blockquote>{reason}</blockquote><div className="actions"><button className="secondary" autoFocus onClick={()=>setConfirm(false)}>돌아가기</button><button className="primary" disabled={busy} onClick={()=>review(true)}>확인 후 시연 종결</button></div></dialog>}
    </div>;
}


